/**
 * GENERATED by scripts/generate-api-types.mjs from the service's /openapi.json.
 * Do not edit by hand - run `npm run gen:api`.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness only: the process can answer requests.
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness: every declared dependency answers.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a canonical order quote */
        post: operations["quote_order_api_v1_orders_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders */
        get: operations["get_orders_api_v1_orders_get"];
        put?: never;
        /** Create order */
        post: operations["create_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order by ID */
        get: operations["get_order_by_id_api_v1_orders__order_id__get"];
        put?: never;
        post?: never;
        /** Delete order */
        delete: operations["delete_order_by_id_api_v1_orders__order_id__delete"];
        options?: never;
        head?: never;
        /** Update order */
        patch: operations["update_order_api_v1_orders__order_id__patch"];
        trace?: never;
    };
    "/api/v1/orders/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get orders by user ID */
        get: operations["get_orders_by_user_id_api_v1_orders_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancel an order */
        patch: operations["cancel_order_api_v1_orders__order_id__cancel_patch"];
        trace?: never;
    };
    "/api/v1/admin/schema/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema for AdminJS */
        get: operations["get_order_schema_for_admin_js_api_v1_admin_schema_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the in-house production queue */
        get: operations["list_production_jobs_api_v1_admin_production_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one production job */
        get: operations["get_production_job_api_v1_admin_production_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/artwork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the print-ready artwork download for a job */
        get: operations["get_production_job_artwork_api_v1_admin_production_jobs__job_id__artwork_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/packing-slip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build the packing slip that ships with the garment */
        get: operations["get_production_job_packing_slip_api_v1_admin_production_jobs__job_id__packing_slip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a queued job to the press */
        post: operations["start_production_job_api_v1_admin_production_jobs__job_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/printed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a job as printed and awaiting post */
        post: operations["mark_production_job_printed_api_v1_admin_production_jobs__job_id__printed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/ship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record the tracking number and notify the customer */
        post: operations["ship_production_job_api_v1_admin_production_jobs__job_id__ship_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/delivered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a job out as delivered */
        post: operations["mark_production_job_delivered_api_v1_admin_production_jobs__job_id__delivered_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Park a job that cannot be worked yet */
        post: operations["hold_production_job_api_v1_admin_production_jobs__job_id__hold_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return a held job to the step it had reached */
        post: operations["resume_production_job_api_v1_admin_production_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/production/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a job off the queue without fulfilling it */
        post: operations["cancel_production_job_api_v1_admin_production_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressType */
        AddressType: {
            /** Street */
            street: string;
            /** City */
            city: string;
            /** Province */
            province: string;
            /** Postal Code */
            postal_code: string;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * ArtworkDownloadSchema
         * @description Where the operator's browser can fetch this job's print file.
         */
        ArtworkDownloadSchema: {
            /** Download Url */
            download_url: string;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /** Content Type */
            content_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
            /** Embedded Dpi */
            embedded_dpi: number;
        };
        /** CancelOrder */
        CancelOrder: {
            /** Reason */
            reason: string;
        };
        /** CancelProductionJobRequest */
        CancelProductionJobRequest: {
            /** Reason */
            reason: string;
        };
        /** CreateOrder */
        CreateOrder: {
            /** Id */
            id?: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * User Email
             * Format: email
             */
            user_email: string;
            /** Amount */
            amount?: number | null;
            /**
             * Currency
             * @default cad
             */
            currency: string;
            /** Payment Intent Id */
            payment_intent_id?: string | null;
            /** Products */
            products: components["schemas"]["OrderProductItem"][];
            address: components["schemas"]["AddressType"];
            /** Shipping Logistic Name */
            shipping_logistic_name?: string | null;
        };
        /**
         * CustomTshirtSpecification
         * @description Immutable production snapshot for a user-generated T-shirt.
         */
        CustomTshirtSpecification: {
            design_asset: components["schemas"]["GeneratedArtworkAsset"];
            /** Prompt */
            prompt: string;
            /** Style */
            style: string;
            /**
             * Size
             * @enum {string}
             */
            size: "S" | "M" | "L";
            /**
             * Garment Color
             * @enum {string}
             */
            garment_color: "white" | "black";
            /**
             * Placement
             * @enum {string}
             */
            placement: "Center Chest" | "Left Top Chest" | "Right Top Chest" | "Left Bottom" | "Right Bottom" | "Center Bottom" | "Oversized Center" | "Full Back" | "Back Upper" | "Back Lower";
            /**
             * Gender
             * @enum {string}
             */
            gender: "Male" | "Female" | "X";
            /** Print Width In */
            print_width_in?: number | null;
            /** Print Height In */
            print_height_in?: number | null;
            /** Effective Dpi */
            effective_dpi?: number | null;
        };
        /**
         * GeneratedArtworkAsset
         * @description Production metadata measured by the image service, never by the browser.
         */
        GeneratedArtworkAsset: {
            /** Key */
            key: string;
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
            /** Embedded Dpi */
            embedded_dpi: number;
            /** Sha256 */
            sha256: string;
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldProductionJobRequest */
        HoldProductionJobRequest: {
            /** Reason */
            reason: string;
        };
        /** MarkPrintedRequest */
        MarkPrintedRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** OrderProductItem */
        OrderProductItem: {
            /** Id */
            id?: string | null;
            /** Variant Id */
            variant_id?: string | null;
            /** Name */
            name?: string | null;
            /** Price */
            price?: number | string | null;
            /** Quantity */
            quantity: number;
            /** Fulfillment Type */
            fulfillment_type?: ("catalog" | "cj" | "custom") | null;
            customization?: components["schemas"]["CustomTshirtSpecification"] | null;
        };
        /** OrderSchema */
        OrderSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * User Email
             * Format: email
             */
            user_email: string;
            /** Amount */
            amount: number;
            /** Subtotal Amount */
            subtotal_amount?: string | null;
            /** Shipping Amount */
            shipping_amount?: string | null;
            /** Tax Amount */
            tax_amount?: string | null;
            /** Shipping Logistic Name */
            shipping_logistic_name?: string | null;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
            /** Delivery Status */
            delivery_status: string;
            /** Payment Intent Id */
            payment_intent_id?: string | null;
            /**
             * Address Id
             * Format: uuid
             */
            address_id: string;
            /** Cj Order Number */
            cj_order_number?: string | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
            /**
             * Amount Cents
             * @description The total in minor units: the only form money leaves this service in.
             */
            readonly amount_cents: number;
        };
        /** PackingSlipAddress */
        PackingSlipAddress: {
            /** Name */
            name?: string | null;
            /** Street */
            street?: string | null;
            /** City */
            city?: string | null;
            /** Province */
            province?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Country */
            country?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** PackingSlipLine */
        PackingSlipLine: {
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price?: number | null;
            /** Currency */
            currency: string;
        };
        /**
         * PackingSlipSchema
         * @description Structured packing slip; the admin UI renders and prints it.
         */
        PackingSlipSchema: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Order Placed At
             * Format: date-time
             */
            order_placed_at: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Customer Email */
            customer_email: string;
            /** Merchant Name */
            merchant_name: string;
            /** Support Email */
            support_email: string;
            ship_to: components["schemas"]["PackingSlipAddress"];
            line: components["schemas"]["PackingSlipLine"];
            print_specification?: components["schemas"]["PrintSpecification"] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * PrintSpecification
         * @description The server-measured production facts the operator prints from.
         */
        PrintSpecification: {
            /** Size */
            size: string;
            /** Garment Color */
            garment_color: string;
            /** Gender */
            gender: string;
            /** Placement */
            placement: string;
            /** Style */
            style: string;
            /** Prompt */
            prompt: string;
            /** Print Width In */
            print_width_in?: number | null;
            /** Print Height In */
            print_height_in?: number | null;
            /** Effective Dpi */
            effective_dpi?: number | null;
            /** Artwork Key */
            artwork_key: string;
            /** Artwork Sha256 */
            artwork_sha256: string;
            /** Artwork Width Px */
            artwork_width_px: number;
            /** Artwork Height Px */
            artwork_height_px: number;
        };
        /**
         * ProductionJobSchema
         * @description One row of the operator's work queue.
         */
        ProductionJobSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * Order Item Id
             * Format: uuid
             */
            order_item_id: string;
            status: components["schemas"]["ProductionJobStatus"];
            /** Quantity */
            quantity: number;
            /** Customer Email */
            customer_email?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Tracking Number */
            tracking_number?: string | null;
            /** Carrier */
            carrier?: string | null;
            /** Tracking Url */
            tracking_url?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Reconciliation Required
             * @default false
             */
            reconciliation_required: boolean;
            /** Cancellation Reason */
            cancellation_reason?: string | null;
            print_specification?: components["schemas"]["PrintSpecification"] | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Started At */
            started_at?: string | null;
            /** Printed At */
            printed_at?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Delivered At */
            delivered_at?: string | null;
            /** Cancelled At */
            cancelled_at?: string | null;
        };
        /**
         * ProductionJobStatus
         * @description Lifecycle of one in-house print job on the operator's work queue.
         * @enum {string}
         */
        ProductionJobStatus: "queued" | "in_production" | "printed" | "shipped" | "delivered" | "on_hold" | "cancelled";
        /**
         * ProductionQueuePage
         * @description A page of the queue plus the counts the dashboard header shows.
         */
        ProductionQueuePage: {
            /** Items */
            items: components["schemas"]["ProductionJobSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Status Counts */
            status_counts?: {
                [key: string]: number;
            };
        };
        /** QuoteOrderRequest */
        QuoteOrderRequest: {
            /** Products */
            products: components["schemas"]["OrderProductItem"][];
            address: components["schemas"]["AddressType"];
            /** Shipping Logistic Name */
            shipping_logistic_name?: string | null;
        };
        /** QuoteOrderResponse */
        QuoteOrderResponse: {
            /** Subtotal Amount */
            subtotal_amount: string;
            /** Shipping Amount */
            shipping_amount: string;
            /** Tax Amount */
            tax_amount: string;
            /** Amount */
            amount: string;
            /** Amount Cents */
            amount_cents: number;
            /** Currency */
            currency: string;
            /** Products */
            products: {
                [key: string]: unknown;
            }[];
            /** Shipping Options */
            shipping_options: components["schemas"]["ShippingOption"][];
            /** Shipping Logistic Name */
            shipping_logistic_name?: string | null;
        };
        /**
         * ShipProductionJobRequest
         * @description Dispatch details entered by the operator when the parcel is posted.
         */
        ShipProductionJobRequest: {
            /** Tracking Number */
            tracking_number: string;
            /** Carrier */
            carrier?: string | null;
            /** Tracking Url */
            tracking_url?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ShippingOption
         * @description One way to ship the CJ part of a cart, priced in the order currency.
         */
        ShippingOption: {
            /** Logistic Name */
            logistic_name: string;
            /** Amount */
            amount: string;
            /** Delivery Time */
            delivery_time?: string | null;
        };
        /** StartProductionJobRequest */
        StartProductionJobRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** UpdateOrder */
        UpdateOrder: {
            /** Delivery Status */
            delivery_status?: string | null;
            /** Cj Order Number */
            cj_order_number?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    quote_order_api_v1_orders_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_api_v1_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"][];
                };
            };
        };
    };
    create_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrder"];
            };
        };
        responses: {
            /** @description New order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_by_id_api_v1_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_order_by_id_api_v1_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_api_v1_orders__order_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_by_user_id_api_v1_orders_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_orders__order_id__cancel_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_schema_for_admin_js_api_v1_admin_schema_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_production_jobs_api_v1_admin_production_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProductionJobStatus"][] | null;
                order_id?: string | null;
                reconciliation_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionQueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_production_job_api_v1_admin_production_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_production_job_artwork_api_v1_admin_production_jobs__job_id__artwork_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkDownloadSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_production_job_packing_slip_api_v1_admin_production_jobs__job_id__packing_slip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackingSlipSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_production_job_api_v1_admin_production_jobs__job_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartProductionJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_production_job_printed_api_v1_admin_production_jobs__job_id__printed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkPrintedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ship_production_job_api_v1_admin_production_jobs__job_id__ship_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipProductionJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_production_job_delivered_api_v1_admin_production_jobs__job_id__delivered_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hold_production_job_api_v1_admin_production_jobs__job_id__hold_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldProductionJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_production_job_api_v1_admin_production_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_production_job_api_v1_admin_production_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelProductionJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionJobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
