/**
 * GENERATED by scripts/generate-api-types.mjs from the service's /openapi.json.
 * Do not edit by hand - run `npm run gen:api`.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness only: the process can answer requests.
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness: every declared dependency answers.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/order-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a canonical order quote */
        post: operations["quote_order_items_api_v1_products_order_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customization/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get custom T-shirt base pricing */
        get: operations["get_custom_tshirt_pricing_api_v1_customization_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Products */
        get: operations["get_all_products_api_v1_products_get"];
        put?: never;
        /**
         * Create product (JSON)
         * @description Create a new product using JSON payload.
         *     Used by AdminJS and API clients. (without images uploads for now)
         */
        post: operations["create_product_json_api_v1_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create product with FormData
         * @description Create a new product with optional image uploads.
         *     Used by frontend forms that need to upload files.
         */
        post: operations["create_product_with_images_api_v1_products_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Products Detailed */
        get: operations["get_all_products_detailed_api_v1_products_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product By Id */
        get: operations["get_product_by_id_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        /** Delete Product By Id */
        delete: operations["delete_product_by_id_api_v1_products__product_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update product (JSON)
         * @description Update a product using JSON payload.
         *     Used by AdminJS and API clients. (without images uploads for now)
         */
        patch: operations["update_product_json_api_v1_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/products/{product_id}/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product By Id Detailed */
        get: operations["get_product_by_id_detailed_api_v1_products__product_id__detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/schema/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema for AdminJS */
        get: operations["get_product_schema_for_admin_js_api_v1_admin_schema_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Categories */
        get: operations["get_all_categories_api_v1_categories_get"];
        put?: never;
        /**
         * Create category (JSON)
         * @description Create a new category using JSON payload.
         *     Used by AdminJS and API clients.
         */
        post: operations["create_category_json_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create category with image (FormData)
         * @description Create a new category with optional image upload.
         *     Used by frontend forms that need to upload files.
         */
        post: operations["create_category_with_image_api_v1_categories_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category By Id */
        get: operations["get_category_by_id_api_v1_categories__category_id__get"];
        put?: never;
        post?: never;
        /** Delete Category By Id */
        delete: operations["delete_category_by_id_api_v1_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category By Id */
        patch: operations["update_category_by_id_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/schema/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema for AdminJS */
        get: operations["get_category_schema_for_admin_js_api_v1_admin_schema_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/users/{user_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review By Product Id And User Id */
        get: operations["get_review_by_product_id_and_user_id_api_v1_products__product_id__users__user_id__reviews_get"];
        /** Update Product Review */
        put: operations["update_product_review_api_v1_products__product_id__users__user_id__reviews_put"];
        /** Create Product Review */
        post: operations["create_product_review_api_v1_products__product_id__users__user_id__reviews_post"];
        /** Delete Product Review */
        delete: operations["delete_product_review_api_v1_products__product_id__users__user_id__reviews_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Reviews */
        get: operations["get_all_reviews_api_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review By Id */
        get: operations["get_review_by_id_api_v1_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reviews By Product Id */
        get: operations["get_reviews_by_product_id_api_v1_products__product_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reviews By User Id */
        get: operations["get_reviews_by_user_id_api_v1_users__user_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/schema/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema for AdminJS */
        get: operations["get_product_reviews_schema_for_admin_js_api_v1_admin_schema_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Image
         * @description Signed-in users only: the quota, and the job, belong to the caller.
         */
        post: operations["generate_image_api_v1_images_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/generations/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation Job Status */
        get: operations["get_generation_job_status_api_v1_images_generations__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{product_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product Images */
        get: operations["get_product_images_api_v1__product_id__images_get"];
        /** Replace Product Images */
        put: operations["replace_product_images_api_v1__product_id__images_put"];
        /** Add Product Images */
        post: operations["add_product_images_api_v1__product_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Images */
        get: operations["get_all_images_api_v1_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image By Id */
        get: operations["get_image_by_id_api_v1_images__image_id__get"];
        put?: never;
        post?: never;
        /** Delete Product Image */
        delete: operations["delete_product_image_api_v1_images__image_id__delete"];
        options?: never;
        head?: never;
        /** Update Product Image */
        patch: operations["update_product_image_api_v1_images__image_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/schema/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema for AdminJS */
        get: operations["get_product_image_schema_for_admin_js_api_v1_admin_schema_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artwork/download-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a signed artwork manifest into a print-file download
         * @description Give an internal caller a short-lived way to fetch one print file.
         *
         *     order_service calls this on behalf of the operator working the in-house
         *     production queue. It is deliberately not exposed through the API gateway:
         *     the artwork belongs to a paying customer and is not a public asset.
         */
        post: operations["create_artwork_download_link_api_v1_artwork_download_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtworkDownloadRequest
         * @description The signed manifest stored on a paid order line.
         *
         *     The manifest is the credential: only a caller holding the manifest this
         *     service issued at generation time can obtain a download for the object.
         */
        ArtworkDownloadRequest: {
            asset: components["schemas"]["GeneratedArtworkAsset"];
        };
        /** ArtworkDownloadResponse */
        ArtworkDownloadResponse: {
            /** Download Url */
            download_url: string;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            /**
             * Content Type
             * @default image/png
             */
            content_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** Body_add_product_images_api_v1__product_id__images_post */
        Body_add_product_images_api_v1__product_id__images_post: {
            /** Images */
            images: string[];
            /** Colors */
            colors: string[];
            /** Color Codes */
            color_codes: string[];
        };
        /** Body_create_category_with_image_api_v1_categories_upload_post */
        Body_create_category_with_image_api_v1_categories_upload_post: {
            /** Name */
            name: string;
            /** Image */
            image: string;
        };
        /** Body_create_product_with_images_api_v1_products_upload_post */
        Body_create_product_with_images_api_v1_products_upload_post: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Brand */
            brand: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: number | string;
            /** In Stock */
            in_stock: boolean;
            /** Images */
            images: string[];
            /** Image Colors */
            image_colors: string[];
            /** Image Color Codes */
            image_color_codes: string[];
        };
        /** Body_replace_product_images_api_v1__product_id__images_put */
        Body_replace_product_images_api_v1__product_id__images_put: {
            /** Images */
            images: string[];
            /** Image Colors */
            image_colors: string[];
            /** Color Codes */
            color_codes: string[];
        };
        /** Body_update_category_by_id_api_v1_categories__category_id__patch */
        Body_update_category_by_id_api_v1_categories__category_id__patch: {
            /** Name */
            name?: string | null;
            /** Image */
            image?: string | null;
        };
        /** Body_update_product_image_api_v1_images__image_id__patch */
        Body_update_product_image_api_v1_images__image_id__patch: {
            /** Image */
            image?: string;
            /** Image Color */
            image_color?: string;
            /** Image Color Code */
            image_color_code?: string;
        };
        /**
         * CategorySchema
         * @description Schema for category responses
         */
        CategorySchema: {
            /** Name */
            name: string;
            /** Cj Category Id */
            cj_category_id?: string | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
        };
        /**
         * CreateCategory
         * @description Schema for creating a new category - internal use after file processing
         */
        CreateCategory: {
            /** Name */
            name: string;
            /** Cj Category Id */
            cj_category_id?: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /**
         * CreateProduct
         * @description Schema for creating a product
         */
        CreateProduct: {
            /** Id */
            id?: string | null;
            /** Pid */
            pid?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** Supplier Category Id */
            supplier_category_id?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Brand
             * @default cjdropshipping
             */
            brand: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: number | string;
            /** In Stock */
            in_stock: boolean;
            /** Sku */
            sku?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Variants */
            variants?: components["schemas"]["CreateProductVariant"][] | null;
            /** Images */
            images?: string[] | null;
        };
        /**
         * CreateProductVariant
         * @description Schema for creating a product variant.
         */
        CreateProductVariant: {
            /** Vid */
            vid: string;
            /** Variant Key */
            variant_key?: string | null;
            /** Variant Name En */
            variant_name_en?: string | null;
            /** Variant Sku */
            variant_sku?: string | null;
            /** Barcode */
            barcode?: string | null;
            /** Variant Image */
            variant_image?: string | null;
            /** Variant Weight */
            variant_weight?: number | string | null;
            /** Variant Length */
            variant_length?: number | null;
            /** Variant Width */
            variant_width?: number | null;
            /** Variant Height */
            variant_height?: number | null;
            /** Variant Sell Price */
            variant_sell_price?: number | string | null;
            /** Variant Sug Sell Price */
            variant_sug_sell_price?: number | string | null;
            /** Retail Price */
            retail_price?: number | string | null;
            /** Inventory Num */
            inventory_num?: number | null;
        };
        /** CreateReview */
        CreateReview: {
            /** Comment */
            comment?: string | null;
            /** Rating */
            rating?: number | null;
        };
        /** CustomTshirtPricingResponse */
        CustomTshirtPricingResponse: {
            /** Base Price */
            base_price: number;
            /**
             * Currency
             * @default USD
             */
            currency: string;
        };
        /** GenerateImageRequest */
        GenerateImageRequest: {
            /** Prompt */
            prompt: string;
            /** Style */
            style: string;
            /**
             * Remove Background
             * @default false
             */
            remove_background: boolean;
        };
        /**
         * GeneratedArtworkAsset
         * @description Production metadata measured by the image service, never by the browser.
         */
        GeneratedArtworkAsset: {
            /** Key */
            key: string;
            /** Width Px */
            width_px: number;
            /** Height Px */
            height_px: number;
            /** Embedded Dpi */
            embedded_dpi: number;
            /** Sha256 */
            sha256: string;
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageGenerationJobStatusResponse
         * @description Returned by the status-poll endpoint.
         */
        ImageGenerationJobStatusResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["ImageJobStatus"];
            /** Image Url */
            image_url?: string | null;
            design_asset?: components["schemas"]["GeneratedArtworkAsset"] | null;
            /** Model */
            model?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ImageGenerationJobSubmitResponse
         * @description Returned immediately (202) when a generation job is accepted.
         */
        ImageGenerationJobSubmitResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["ImageJobStatus"];
            /** Remaining Generations */
            remaining_generations: number;
            /** Generation Limit */
            generation_limit: number;
        };
        /**
         * ImageJobStatus
         * @enum {string}
         */
        ImageJobStatus: "pending" | "running" | "completed" | "failed";
        /** ImageType */
        ImageType: {
            /** Image Color */
            image_color?: string | null;
            /** Image Color Code */
            image_color_code?: string | null;
            /** Image Url */
            image_url: string;
        };
        /** OrderQuoteLine */
        OrderQuoteLine: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Variant Id */
            variant_id?: string | null;
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: string;
            /**
             * Fulfillment Type
             * @enum {string}
             */
            fulfillment_type: "catalog" | "cj";
            /** Supplier Id */
            supplier_id?: string | null;
            /** Variant Snapshot */
            variant_snapshot?: {
                [key: string]: unknown;
            } | null;
        };
        /** OrderQuoteLineRequest */
        OrderQuoteLineRequest: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Variant Id */
            variant_id?: string | null;
            /** Quantity */
            quantity: number;
        };
        /** OrderQuoteRequest */
        OrderQuoteRequest: {
            /** Items */
            items: components["schemas"]["OrderQuoteLineRequest"][];
        };
        /** OrderQuoteResponse */
        OrderQuoteResponse: {
            /**
             * Currency
             * @default CAD
             */
            currency: string;
            /** Items */
            items: components["schemas"]["OrderQuoteLine"][];
            /** Total Amount */
            total_amount: string;
        };
        /**
         * ProductBase
         * @description Base product schema with common attributes
         */
        ProductBase: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pid */
            pid?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Brand */
            brand: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: string;
            /** In Stock */
            in_stock: boolean;
            /** Sku */
            sku?: string | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
        };
        /**
         * ProductImageSchema
         * @description Schema for product image representation.
         */
        ProductImageSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Image Url */
            image_url: string;
            /** Image Color */
            image_color?: string | null;
            /** Image Color Code */
            image_color_code?: string | null;
        };
        /**
         * ProductSchema
         * @description Schema for product responses
         */
        ProductSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pid */
            pid?: string | null;
            /** Supplier Id */
            supplier_id?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Brand */
            brand: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: string;
            /** In Stock */
            in_stock: boolean;
            /** Sku */
            sku?: string | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
            /** Reviews */
            reviews?: components["schemas"]["ReviewSchema"][] | null;
            category?: components["schemas"]["CategorySchema"] | null;
            /** Images */
            images: components["schemas"]["ImageType"][];
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["ProductVariantBase"][];
        };
        /**
         * ProductVariantBase
         * @description Base schema for product variants.
         */
        ProductVariantBase: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Vid */
            vid: string;
            /** Variant Key */
            variant_key?: string | null;
            /** Variant Name En */
            variant_name_en?: string | null;
            /** Variant Sku */
            variant_sku?: string | null;
            /** Barcode */
            barcode?: string | null;
            /** Variant Image */
            variant_image?: string | null;
            /** Variant Weight */
            variant_weight?: string | null;
            /** Variant Length */
            variant_length?: number | null;
            /** Variant Width */
            variant_width?: number | null;
            /** Variant Height */
            variant_height?: number | null;
            /** Variant Sell Price */
            variant_sell_price?: string | null;
            /** Variant Sug Sell Price */
            variant_sug_sell_price?: string | null;
            /** Retail Price */
            retail_price?: string | null;
            /** Inventory Num */
            inventory_num?: number | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
        };
        /**
         * ReviewSchema
         * @description Schema for review responses
         */
        ReviewSchema: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Comment */
            comment?: string | null;
            /** Rating */
            rating?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
        };
        /**
         * UpdateProduct
         * @description Schema for updating an existing product
         */
        UpdateProduct: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Brand */
            brand?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Price */
            price?: number | string | null;
            /** In Stock */
            in_stock?: boolean | null;
        };
        /** UpdateReview */
        UpdateReview: {
            /** Comment */
            comment?: string | null;
            /** Rating */
            rating?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    quote_order_items_api_v1_products_order_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_custom_tshirt_pricing_api_v1_customization_pricing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomTshirtPricingResponse"];
                };
            };
        };
    };
    get_all_products_api_v1_products_get: {
        parameters: {
            query?: {
                /** @description Number of records to skip */
                offset?: number;
                /** @description Maximum number of records to return */
                limit?: number;
                sort_order?: string | null;
                sort_by?: string | null;
                name?: string | null;
                brand?: string | null;
                category_id?: string | null;
                search_term?: string | null;
                in_stock?: boolean | null;
                price?: number | string | null;
                min_price?: number | string | null;
                max_price?: number | string | null;
                quantity?: number | null;
                min_quantity?: number | null;
                max_quantity?: number | null;
                date_created_from?: string | null;
                date_created_to?: string | null;
                date_updated_from?: string | null;
                date_updated_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductBase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_json_api_v1_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProduct"];
            };
        };
        responses: {
            /** @description New product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_with_images_api_v1_products_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_product_with_images_api_v1_products_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_products_detailed_api_v1_products_detailed_get: {
        parameters: {
            query?: {
                /** @description Number of records to skip */
                offset?: number;
                /** @description Maximum number of records to return */
                limit?: number;
                sort_order?: string | null;
                sort_by?: string | null;
                name?: string | null;
                brand?: string | null;
                category_id?: string | null;
                search_term?: string | null;
                in_stock?: boolean | null;
                price?: number | string | null;
                min_price?: number | string | null;
                max_price?: number | string | null;
                quantity?: number | null;
                min_quantity?: number | null;
                max_quantity?: number | null;
                date_created_from?: string | null;
                date_created_to?: string | null;
                date_updated_from?: string | null;
                date_updated_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All products with relations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_by_id_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_by_id_api_v1_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_json_api_v1_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProduct"];
            };
        };
        responses: {
            /** @description Product updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_by_id_detailed_api_v1_products__product_id__detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product by ID with relations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_schema_for_admin_js_api_v1_admin_schema_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_all_categories_api_v1_categories_get: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_json_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategory"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_with_image_api_v1_categories_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_category_with_image_api_v1_categories_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_by_id_api_v1_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_by_id_api_v1_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_by_id_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_category_by_id_api_v1_categories__category_id__patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorySchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_schema_for_admin_js_api_v1_admin_schema_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_review_by_product_id_and_user_id_api_v1_products__product_id__users__user_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get specific user's review for a product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_review_api_v1_products__product_id__users__user_id__reviews_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReview"];
            };
        };
        responses: {
            /** @description Update product review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_review_api_v1_products__product_id__users__user_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReview"];
            };
        };
        responses: {
            /** @description Create product review */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_review_api_v1_products__product_id__users__user_id__reviews_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete product review */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_reviews_api_v1_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"][];
                };
            };
        };
    };
    get_review_by_id_api_v1_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get review by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviews_by_product_id_api_v1_products__product_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all reviews for a product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviews_by_user_id_api_v1_users__user_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all reviews by user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_reviews_schema_for_admin_js_api_v1_admin_schema_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    generate_image_api_v1_images_generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageRequest"];
            };
        };
        responses: {
            /** @description Submit image generation job */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageGenerationJobSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_job_status_api_v1_images_generations__job_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Poll background image generation job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageGenerationJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_images_api_v1__product_id__images_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all images for a product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_product_images_api_v1__product_id__images_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_product_images_api_v1__product_id__images_put"];
            };
        };
        responses: {
            /** @description Replace all product images */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_product_images_api_v1__product_id__images_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_product_images_api_v1__product_id__images_post"];
            };
        };
        responses: {
            /** @description Add images to product */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_images_api_v1_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all images */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageSchema"][];
                };
            };
        };
    };
    get_image_by_id_api_v1_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get image by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_image_api_v1_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete image by ID */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_image_api_v1_images__image_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_product_image_api_v1_images__image_id__patch"];
            };
        };
        responses: {
            /** @description Update single image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_image_schema_for_admin_js_api_v1_admin_schema_images_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_artwork_download_link_api_v1_artwork_download_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtworkDownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtworkDownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
