/**
 * GENERATED by scripts/generate-api-types.mjs from the service's /openapi.json.
 * Do not edit by hand - run `npm run gen:api`.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness only: the process can answer requests.
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness: every declared dependency answers.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active shipping methods */
        get: operations["list_active_shipping_methods_api_v1_shipping_methods_get"];
        put?: never;
        /** Create a shipping method */
        post: operations["create_shipping_method_api_v1_shipping_methods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/methods/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all shipping methods */
        get: operations["list_all_shipping_methods_api_v1_shipping_methods_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/methods/{method_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a shipping method */
        get: operations["get_shipping_method_api_v1_shipping_methods__method_id__get"];
        put?: never;
        post?: never;
        /** Delete a shipping method */
        delete: operations["delete_shipping_method_api_v1_shipping_methods__method_id__delete"];
        options?: never;
        head?: never;
        /** Update a shipping method */
        patch: operations["update_shipping_method_api_v1_shipping_methods__method_id__patch"];
        trace?: never;
    };
    "/api/v1/shipping/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate shipping rates */
        post: operations["calculate_shipping_rates_api_v1_shipping_rates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a shipment */
        post: operations["create_shipment_api_v1_shipments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shipment by ID */
        get: operations["get_shipment_by_id_api_v1_shipments__shipment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a shipment */
        patch: operations["update_shipment_api_v1_shipments__shipment_id__patch"];
        trace?: never;
    };
    "/api/v1/shipments/order/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shipment by order ID */
        get: operations["get_shipment_by_order_id_api_v1_shipments_order__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateShipment */
        CreateShipment: {
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * User Email
             * @default
             */
            user_email: string;
            /**
             * Method Id
             * Format: uuid
             */
            method_id: string;
            destination: components["schemas"]["ShippingAddress"];
        };
        /** CreateShippingMethod */
        CreateShippingMethod: {
            /** Name */
            name: string;
            /** Carrier */
            carrier: string;
            /** Base Cost */
            base_cost: number | string;
            /** Estimated Days */
            estimated_days: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ShipmentSchema */
        ShipmentSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Method Id
             * Format: uuid
             */
            method_id: string;
            /** Tracking Number */
            tracking_number?: string | null;
            /** Status */
            status: string;
            /** Estimated Delivery */
            estimated_delivery?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Delivered At */
            delivered_at?: string | null;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
        };
        /** ShippingAddress */
        ShippingAddress: {
            /** Street */
            street: string;
            /** City */
            city: string;
            /** Province */
            province: string;
            /** Postal Code */
            postal_code: string;
            /**
             * Country
             * @default US
             */
            country: string;
        };
        /** ShippingMethodSchema */
        ShippingMethodSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Carrier */
            carrier: string;
            /** Base Cost */
            base_cost: string;
            /** Estimated Days */
            estimated_days: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Date Created
             * Format: date-time
             */
            date_created: string;
            /** Date Updated */
            date_updated?: string | null;
        };
        /** ShippingRateRequest */
        ShippingRateRequest: {
            destination: components["schemas"]["ShippingAddress"];
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** UpdateShipment */
        UpdateShipment: {
            /** Status */
            status?: string | null;
            /** Tracking Number */
            tracking_number?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Delivered At */
            delivered_at?: string | null;
        };
        /** UpdateShippingMethod */
        UpdateShippingMethod: {
            /** Name */
            name?: string | null;
            /** Carrier */
            carrier?: string | null;
            /** Base Cost */
            base_cost?: number | string | null;
            /** Estimated Days */
            estimated_days?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_active_shipping_methods_api_v1_shipping_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingMethodSchema"][];
                };
            };
        };
    };
    create_shipping_method_api_v1_shipping_methods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShippingMethod"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingMethodSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_shipping_methods_api_v1_shipping_methods_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingMethodSchema"][];
                };
            };
        };
    };
    get_shipping_method_api_v1_shipping_methods__method_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                method_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingMethodSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shipping_method_api_v1_shipping_methods__method_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                method_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shipping_method_api_v1_shipping_methods__method_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                method_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShippingMethod"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingMethodSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_shipping_rates_api_v1_shipping_rates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShippingRateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shipment_api_v1_shipments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShipment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_by_id_api_v1_shipments__shipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shipment_api_v1_shipments__shipment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShipment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_by_order_id_api_v1_shipments_order__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
