/**
 * GENERATED by scripts/generate-api-types.mjs from the service's /openapi.json.
 * Do not edit by hand - run `npm run gen:api`.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness only: the process can answer requests.
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness: every declared dependency answers.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cjdropshipping/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Products From Cjdropshipping
         * @description Search products directly from CJDropshipping.
         */
        get: operations["get_products_from_cjdropshipping_api_v1_cjdropshipping_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cjdropshipping/products/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cjdropshipping Product Details
         * @description Fetch raw product details from CJDropshipping by pid.
         */
        get: operations["get_cjdropshipping_product_details_api_v1_cjdropshipping_products__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cjdropshipping/products/{pid}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synchronize one CJ Dropshipping product
         * @description Fetch one CJ product by pid and emit a single import event.
         */
        post: operations["sync_cjdropshipping_product_api_v1_cjdropshipping_products__pid__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cjdropshipping/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synchronize CJ Dropshipping products
         * @description Pull products from CJDropshipping and emit import events to product_service.
         */
        post: operations["sync_cjdropshipping_products_api_v1_cjdropshipping_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suppliers/{supplier_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a manual supplier sync
         * @description Manually trigger a supplier sync and emit product import events.
         */
        post: operations["sync_supplier_products_api_v1_suppliers__supplier_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cjdropshipping/freight/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quote CJ shipping for a cart at checkout
         * @description Price the CJ-fulfilled part of a cart for one destination.
         *
         *     Returns 422 when CJ cannot ship the cart to the requested country, which is
         *     the signal for checkout to block the order rather than sell an item that
         *     can never be delivered.
         */
        post: operations["quote_cjdropshipping_freight_api_v1_cjdropshipping_freight_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CJFreightOption
         * @description A single shippable option returned by CJ freightCalculate.
         */
        CJFreightOption: {
            /** Logistic Name */
            logistic_name: string;
            /** Price */
            price: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Delivery Time */
            delivery_time?: string | null;
            /** Weight Grams */
            weight_grams?: string | null;
        };
        /**
         * CJFreightQuoteItem
         * @description One cart line, addressed by the local product/variant pair.
         */
        CJFreightQuoteItem: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Variant Id
             * Format: uuid
             */
            variant_id: string;
            /** Quantity */
            quantity: number;
        };
        /**
         * CJFreightQuoteRequest
         * @description Everything CJ needs to price shipping for a cart at checkout time.
         */
        CJFreightQuoteRequest: {
            /** Country Code */
            country_code: string;
            /** Postal Code */
            postal_code?: string | null;
            /** Items */
            items: components["schemas"]["CJFreightQuoteItem"][];
        };
        /**
         * CJFreightQuoteResponse
         * @description Shipping options for one destination, cheapest first.
         */
        CJFreightQuoteResponse: {
            /** Country Code */
            country_code: string;
            /** Postal Code */
            postal_code?: string | null;
            /** Options */
            options: components["schemas"]["CJFreightOption"][];
        };
        /**
         * CJProductPreview
         * @description Supplier-service response model for a CJ product list preview.
         */
        CJProductPreview: {
            /** Pid */
            pid: string;
            /** Name */
            name: string;
            /** Sku */
            sku?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Price */
            price: string;
            /** Quantity */
            quantity: number;
            /** In Stock */
            in_stock: boolean;
            /** Supplier Category Id */
            supplier_category_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SupplierSyncRunSummary
         * @description Result of a single supplier sync run.
         */
        SupplierSyncRunSummary: {
            /** Supplier Id */
            supplier_id: string;
            /**
             * Fetch Id
             * Format: uuid
             */
            fetch_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Products Fetched
             * @default 0
             */
            products_fetched: number;
            /**
             * Products Emitted
             * @default 0
             */
            products_emitted: number;
            /**
             * Total Batches
             * @default 0
             */
            total_batches: number;
            /**
             * Processed Batches
             * @default 0
             */
            processed_batches: number;
            /**
             * Products Imported
             * @default 0
             */
            products_imported: number;
            /**
             * Products Updated
             * @default 0
             */
            products_updated: number;
            /**
             * Products Failed
             * @default 0
             */
            products_failed: number;
            /** Errors */
            errors?: string[];
            /**
             * Status
             * @default pending
             */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_products_from_cjdropshipping_api_v1_cjdropshipping_products_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                keyWord?: string | null;
                categoryId?: string | null;
                lv2categoryList?: string[] | null;
                lv3categoryList?: string[] | null;
                countryCode?: string | null;
                isWarehouse?: boolean | null;
                verifiedWarehouse?: (0 | 1 | 2) | null;
                startSellPrice?: number | string | null;
                endSellPrice?: number | string | null;
                startWarehouseInventory?: number | null;
                endWarehouseInventory?: number | null;
                addMarkStatus?: (0 | 1) | null;
                productType?: number | null;
                productFlag?: (0 | 1 | 2 | 3) | null;
                supplierId?: string | null;
                hasCertification?: (0 | 1) | null;
                isSelfPickup?: (0 | 1) | null;
                customization?: (0 | 1) | null;
                timeStart?: number | null;
                timeEnd?: number | null;
                zonePlatform?: string | null;
                sort?: ("desc" | "asc") | null;
                orderBy?: (0 | 1 | 2 | 3 | 4) | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products from CJDropshipping */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CJProductPreview"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cjdropshipping_product_details_api_v1_cjdropshipping_products__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw CJDropshipping product details by pid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_cjdropshipping_product_api_v1_cjdropshipping_products__pid__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierSyncRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_cjdropshipping_products_api_v1_cjdropshipping_sync_post: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                keyWord?: string | null;
                categoryId?: string | null;
                lv2categoryList?: string[] | null;
                lv3categoryList?: string[] | null;
                countryCode?: string | null;
                isWarehouse?: boolean | null;
                verifiedWarehouse?: (0 | 1 | 2) | null;
                startSellPrice?: number | string | null;
                endSellPrice?: number | string | null;
                startWarehouseInventory?: number | null;
                endWarehouseInventory?: number | null;
                addMarkStatus?: (0 | 1) | null;
                productType?: number | null;
                productFlag?: (0 | 1 | 2 | 3) | null;
                supplierId?: string | null;
                hasCertification?: (0 | 1) | null;
                isSelfPickup?: (0 | 1) | null;
                customization?: (0 | 1) | null;
                timeStart?: number | null;
                timeEnd?: number | null;
                zonePlatform?: string | null;
                sort?: ("desc" | "asc") | null;
                orderBy?: (0 | 1 | 2 | 3 | 4) | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierSyncRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_supplier_products_api_v1_suppliers__supplier_id__sync_post: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                keyWord?: string | null;
                categoryId?: string | null;
                lv2categoryList?: string[] | null;
                lv3categoryList?: string[] | null;
                countryCode?: string | null;
                isWarehouse?: boolean | null;
                verifiedWarehouse?: (0 | 1 | 2) | null;
                startSellPrice?: number | string | null;
                endSellPrice?: number | string | null;
                startWarehouseInventory?: number | null;
                endWarehouseInventory?: number | null;
                addMarkStatus?: (0 | 1) | null;
                productType?: number | null;
                productFlag?: (0 | 1 | 2 | 3) | null;
                supplierId?: string | null;
                hasCertification?: (0 | 1) | null;
                isSelfPickup?: (0 | 1) | null;
                customization?: (0 | 1) | null;
                timeStart?: number | null;
                timeEnd?: number | null;
                zonePlatform?: string | null;
                sort?: ("desc" | "asc") | null;
                orderBy?: (0 | 1 | 2 | 3 | 4) | null;
            };
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierSyncRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_cjdropshipping_freight_api_v1_cjdropshipping_freight_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CJFreightQuoteRequest"];
            };
        };
        responses: {
            /** @description CJ Dropshipping shipping options, cheapest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CJFreightQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
