import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    'app/pages/**/*.{js,ts,jsx,tsx,mdx}',
    'app/components/**/*.{js,ts,jsx,tsx,mdx}',
    'app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
      "brand-lime": "#D4FF5F",
      surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        secondary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e1dfdf",
        "on-secondary-container": "#626262",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "on-tertiary-container": "#838484",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-lg": "80px",
        "margin-desktop": "64px",
        gutter: "24px",
        unit: "8px",
        "stack-md": "32px",
        "stack-sm": "12px",
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-bold": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-xl": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "price-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-hanken-grotesk)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "2rem",
        full: "9999px",
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "price-lg": ["24px", { lineHeight: "32px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
export default config;
