services:
  user-service-test:
    build:
      context: ./user_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  product-service-test:
    build:
      context: ./product_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  payment-service-test:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  cart-service-test:
    build:
      context: ./cart_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  wishlist-service-test:
    build:
      context: ./wishlist_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  order-service-test:
    build:
      context: ./order_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  notification-service-test:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  shipping-service-test:
    build:
      context: ./shipping_service
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "no"

  api-gateway-test:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./shared:/app/shared:ro
    networks:
      - usernet
    profiles:
      - test
    env_file:
      - .env
    restart: "no"
