"""baseline notification schema

Revision ID: 012487ca2c66
Revises: 
Create Date: 2026-09-09 16:54:31.615672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012487ca2c66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_date_created', 'notifications', ['date_created'], unique=False)
    op.create_index('idx_notification_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notification_user_id', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_user_id', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_index('idx_notification_is_read', table_name='notifications')
    op.drop_index('idx_notification_date_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
