"""baseline shipping schema

Revision ID: fe33062051ed
Revises: 
Create Date: 2026-09-09 16:54:26.876323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe33062051ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_events_event_type', 'outbox_events', ['event_type'], unique=False)
    op.create_index('idx_outbox_events_processed', 'outbox_events', ['processed'], unique=False)
    op.create_index('idx_outbox_events_retry', 'outbox_events', ['processed', 'next_retry_at'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('base_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shipping_methods_is_active', 'shipping_methods', ['is_active'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['shipping_methods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_shipments_order_id', 'shipments', ['order_id'], unique=True)
    op.create_index('idx_shipments_status', 'shipments', ['status'], unique=False)
    op.create_index('idx_shipments_user_id', 'shipments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shipments_user_id', table_name='shipments')
    op.drop_index('idx_shipments_status', table_name='shipments')
    op.drop_index('idx_shipments_order_id', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('idx_shipping_methods_is_active', table_name='shipping_methods')
    op.drop_table('shipping_methods')
    op.drop_index('idx_outbox_events_retry', table_name='outbox_events')
    op.drop_index('idx_outbox_events_processed', table_name='outbox_events')
    op.drop_index('idx_outbox_events_event_type', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
