"""baseline product schema

Revision ID: 1ee7bfc89e7e
Revises: 
Create Date: 2026-09-09 16:56:05.233498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ee7bfc89e7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('line_key', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_key', name='uq_inventory_order_line')
    )
    op.create_index('idx_inventory_reservation_order', 'inventory_reservations', ['order_id'], unique=False)
    op.create_index('idx_inventory_reservation_status', 'inventory_reservations', ['status'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_events_event_type', 'outbox_events', ['event_type'], unique=False)
    op.create_index('idx_outbox_events_processed', 'outbox_events', ['processed'], unique=False)
    op.create_index('idx_outbox_events_retry', 'outbox_events', ['processed', 'next_retry_at'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cj_category_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cj_category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_product_categories_cj_id', 'product_categories', ['cj_category_id'], unique=True)
    op.create_index('idx_product_categories_name', 'product_categories', ['name'], unique=False)
    op.create_table('retained_artwork',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artwork_key', sa.String(length=512), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=500), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retained_artwork_key', 'retained_artwork', ['artwork_key'], unique=False)
    op.create_index('idx_retained_artwork_order', 'retained_artwork', ['order_id'], unique=False)
    op.create_index('idx_retained_artwork_released', 'retained_artwork', ['released_at'], unique=False)
    op.create_table('supplier_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.String(length=100), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('total_batches', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_supplier_import_batch_event_id'),
    sa.UniqueConstraint('supplier_id', 'batch_id', name='uq_supplier_import_batch_supplier_batch')
    )
    op.create_index('idx_supplier_import_batch_fetch_id', 'supplier_import_batches', ['fetch_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.String(), nullable=True),
    sa.Column('supplier_category_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_brand', 'products', ['brand'], unique=False)
    op.create_index('idx_product_brand_in_stock', 'products', ['brand', 'in_stock'], unique=False)
    op.create_index('idx_product_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_product_category_in_stock', 'products', ['category_id', 'in_stock'], unique=False)
    op.create_index('idx_product_category_price', 'products', ['category_id', 'price'], unique=False)
    op.create_index('idx_product_in_stock', 'products', ['in_stock'], unique=False)
    op.create_index('idx_product_in_stock_date_created', 'products', ['in_stock', 'date_created'], unique=False)
    op.create_index('idx_product_in_stock_partial', 'products', ['id', 'date_created'], unique=False, postgresql_where='in_stock = true')
    op.create_index('idx_product_name', 'products', ['name'], unique=False)
    op.create_index('idx_product_pid', 'products', ['pid'], unique=False)
    op.create_index('idx_product_price', 'products', ['price'], unique=False)
    op.create_index('idx_product_supplier_pid', 'products', ['supplier_id', 'pid'], unique=True)
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_color', sa.String(), nullable=True),
    sa.Column('image_color_code', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_image_product_id', 'product_images', ['product_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_review_date_created', 'product_reviews', ['date_created'], unique=False)
    op.create_index('idx_product_review_product_id', 'product_reviews', ['product_id'], unique=False)
    op.create_index('idx_product_review_product_rating', 'product_reviews', ['product_id', 'rating'], unique=False)
    op.create_index('idx_product_review_user_id', 'product_reviews', ['user_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('vid', sa.String(), nullable=False),
    sa.Column('variant_key', sa.String(), nullable=True),
    sa.Column('variant_name_en', sa.String(), nullable=True),
    sa.Column('variant_sku', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('variant_image', sa.String(), nullable=True),
    sa.Column('variant_weight', sa.Numeric(), nullable=True),
    sa.Column('variant_length', sa.Integer(), nullable=True),
    sa.Column('variant_width', sa.Integer(), nullable=True),
    sa.Column('variant_height', sa.Integer(), nullable=True),
    sa.Column('variant_sell_price', sa.Numeric(), nullable=True),
    sa.Column('variant_sug_sell_price', sa.Numeric(), nullable=True),
    sa.Column('inventory_num', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'vid', name='uq_product_variant_product_id_vid')
    )
    op.create_index('idx_product_variant_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('idx_product_variant_vid', 'product_variants', ['vid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_variant_vid', table_name='product_variants')
    op.drop_index('idx_product_variant_product_id', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('idx_product_review_user_id', table_name='product_reviews')
    op.drop_index('idx_product_review_product_rating', table_name='product_reviews')
    op.drop_index('idx_product_review_product_id', table_name='product_reviews')
    op.drop_index('idx_product_review_date_created', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index('idx_product_image_product_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('idx_product_supplier_pid', table_name='products')
    op.drop_index('idx_product_price', table_name='products')
    op.drop_index('idx_product_pid', table_name='products')
    op.drop_index('idx_product_name', table_name='products')
    op.drop_index('idx_product_in_stock_partial', table_name='products', postgresql_where='in_stock = true')
    op.drop_index('idx_product_in_stock_date_created', table_name='products')
    op.drop_index('idx_product_in_stock', table_name='products')
    op.drop_index('idx_product_category_price', table_name='products')
    op.drop_index('idx_product_category_in_stock', table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_index('idx_product_brand_in_stock', table_name='products')
    op.drop_index('idx_product_brand', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_supplier_import_batch_fetch_id', table_name='supplier_import_batches')
    op.drop_table('supplier_import_batches')
    op.drop_index('idx_retained_artwork_released', table_name='retained_artwork')
    op.drop_index('idx_retained_artwork_order', table_name='retained_artwork')
    op.drop_index('idx_retained_artwork_key', table_name='retained_artwork')
    op.drop_table('retained_artwork')
    op.drop_index('idx_product_categories_name', table_name='product_categories')
    op.drop_index('idx_product_categories_cj_id', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index('idx_outbox_events_retry', table_name='outbox_events')
    op.drop_index('idx_outbox_events_processed', table_name='outbox_events')
    op.drop_index('idx_outbox_events_event_type', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('idx_inventory_reservation_status', table_name='inventory_reservations')
    op.drop_index('idx_inventory_reservation_order', table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    # ### end Alembic commands ###
