FROM python:3.12-slim AS builder
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PATH="/root/.local/bin:${PATH}"

RUN apt-get update && apt-get install -y --no-install-recommends gcc python3-dev libpq-dev curl \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev




FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends libpq5 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && addgroup --system --gid 1007 taskiq_group \
    && adduser --system --uid 1007 --ingroup taskiq_group taskiq_user \
    && chown -R taskiq_user:taskiq_group /app

COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"
COPY --chown=taskiq_user:taskiq_group . .

USER taskiq_user

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
    CMD ps aux | grep -v grep | grep "taskiq worker" || exit 1

# workers=2 means 2 concurrent task executors in this container
CMD ["taskiq", "worker", "tasks.broker:broker", "tasks.email_tasks", "--workers", "1"]
