"""outbox retry columns

Revision ID: 52d693f24c4c
Revises: fcec369746e3
Create Date: 2026-09-09 16:54:44.139413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d693f24c4c'
down_revision: Union[str, Sequence[str], None] = 'fcec369746e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('outbox_events', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('outbox_events', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_outbox_events_retry', 'outbox_events', ['processed', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_outbox_events_retry', table_name='outbox_events')
    op.drop_column('outbox_events', 'next_retry_at')
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'attempts')
    # ### end Alembic commands ###
